### get users

@token = 13|ImLH2ieR2Th21Cg0t6lLuuQ6ebofmWV13zAd7u9I
@baseUrl = http://localhost:8000/api


GET {{baseUrl}}/users
Authorization: : Bearer {{token}}

### LOGIN
POST {{baseUrl}}/login
content-type : application/json

{
    "email": "anastasia@anastasia.com",
    "password": "Anastasia1234!"
}